# Generated by Django 4.0.4 on 2024-06-07 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LeSorelle', '0002_alter_blog_description_alter_blog_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=2, upload_to='blog/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
