# Generated by Django 5.0 on 2024-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0003_remove_reserva_user_reserva_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
