# Generated by Django 5.0 on 2024-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0005_alter_reserva_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.CharField(choices=[('08:00', '08:00 AM'), ('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('20:00', '20:00 PM')], default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.CharField(choices=[('08:00', '08:00 AM'), ('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('20:00', '20:00 PM')], null=True),
        ),
    ]
