# Generated by Django 5.0 on 2024-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0006_reserva_horario_alter_reserva_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('20:00', '20:00')], null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('20:00', '20:00')], max_length=5),
        ),
    ]
