# Generated by Django 5.0 on 2024-05-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0009_remove_reserva_horario_remove_reserva_name_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='email',
        ),
    ]
