# Generated by Django 5.0 on 2024-05-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0010_remove_reserva_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='peso',
        ),
    ]
