# Generated by Django 5.0 on 2024-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0012_food_status_reserva_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
