# Generated by Django 5.0 on 2024-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0013_alter_reserva_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pratos_adicionais',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
