# Generated by Django 5.0 on 2024-05-15 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0014_reserva_pratos_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pratos_adicionais',
        ),
        migrations.CreateModel(
            name='PratoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeSorelle.reserva')),
            ],
        ),
    ]
