# Generated by Django 5.0 on 2024-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0015_remove_reserva_pratos_adicionais_pratoadicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratoadicional',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pratoadicional',
            name='peso',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
