# Generated by Django 5.0 on 2024-05-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0016_alter_pratoadicional_nome_alter_pratoadicional_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pratoadicional',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pratoadicional',
            name='peso',
        ),
        migrations.AddField(
            model_name='pratoadicional',
            name='food',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pratos_adicionais_food', to='LeSorelle.food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pratoadicional',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos_adicionais_reserva', to='LeSorelle.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_principal', to='LeSorelle.food'),
        ),
    ]
