# Generated by Django 5.0 on 2024-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0017_remove_pratoadicional_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratoadicional',
            name='peso',
            field=models.CharField(default=400, max_length=10),
            preserve_default=False,
        ),
    ]
