# Generated by Django 5.0 on 2024-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0018_pratoadicional_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratoadicional',
            name='peso',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
