# Generated by Django 5.0 on 2024-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0020_pratoadicional_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_preparo', 'Em Preparo'), ('pronto', 'Pronto'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
