# Generated by Django 4.0.4 on 2024-05-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeSorelle', '0022_notification_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratoadicional',
            name='modo',
            field=models.CharField(choices=[('fresco', 'Fresco'), ('congelado', 'Congelado'), ('aquecido', 'Aquecido')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='modo',
            field=models.CharField(choices=[('fresco', 'Fresco'), ('congelado', 'Congelado'), ('Aquecido', 'Aquecido')], max_length=10, null=True),
        ),
    ]
